version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    # machine:
    #   image: linux-cuda-12:default
    # resource_class: gpu.nvidia.medium
    docker: # executor type
      - image: cimg/python:stable
    steps:
      - checkout
      - run: which pip
      - run: $ pip install git+https://github.com/huggingface/diffusers transformers accelerate
      - run: python vidmaker.py
      - store_artifacts:
          path: vid.mp4
          destination: vid.mp4
# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
