version: '2.1'
orbs:
  win: circleci/windows@5.0
jobs:
  build:
    docker: nvidia/cuda
    steps:
      - run: python --version
      - run: pip install git+https://github.com/huggingface/diffusers transformers accelerate

workflows:
  my-workflow:
    jobs:
      - build