version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    machine:
      image: linux-cuda-12:default
    resource_class: gpu.nvidia.medium
    steps:
      - checkout
      - run: which pip
# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
