version: '2.1'
orbs:
  win: circleci/windows@5.0
jobs:
  build:
    docker: 
      - image: 2.3.1-cuda11.8-cudnn8-runtime
    steps:
      - run: python --version
      - run: pip install git+https://github.com/huggingface/diffusers transformers accelerate

workflows:
  my-workflow:
    jobs:
      - build